POST http://localhost:8000/products HTTP/1.1
Content-Type: application/json

{
    "name": "My Product",
    "price": 100
}

###

Get http://localhost:8000/products HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTc1MDI2MzksInN1YiI6IjM0ZWY4M2RiLTA4ZTEtNGQ4YS04ZWVhLWE5ODQ0YzA0OGE4OSJ9.vpAcCRnUBV4hSlsqZhghQ7Nl4Je5Q6Jj5_vhYOYz2Qc

###

Get http://localhost:8000/products/334a8bdd-cb82-481e-9dfe-4cd99bc2492c HTTP/1.1

###

PUT http://localhost:8000/products/334a8bdd-cb82-481e-9dfe-4cd99bc2492c HTTP/1.1
Content-Type: application/json

{
    "name": "My Product Update",
    "price": 200
}

###
DELETE http://localhost:8000/products/334a8bdd-cb82-481e-9dfe-4cd99bc2492c HTTP/1.1